


<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>Dictionary_Application</RootNamespace>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Models\User.fs" />
		<Compile Include="Models\Word.fs" />
		

		<Compile Include="Services\FileIO.fs" />
		<Compile Include="Services\CRUD.fs" />
		<Compile Include="Services\UserAuth.fs" />
		<Compile Include="Services\Search.fs" />
		<Compile Include="Services\ErrorHandler.fs" />

		<Compile Include="UI\MainForm.fs" />
	</ItemGroup>

</Project>
