<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Dictionary_Application</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<!-- Models must always come first -->
		<Compile Include="Models\Word.fs" />

		<!-- Services come next -->
		<Compile Include="Services\CRUD.fs" />
		<Compile Include="Services\Search.fs" />
		<Compile Include="Services\FileIO.fs" />
		<Compile Include="Services\ErrorHandler.fs" />

		<!-- UI comes after Services -->
		<Compile Include="UI\Menu.fs" />

		<!-- Program last -->
		<Compile Include="Program.fs" />
	</ItemGroup>


	<ItemGroup>
    <Folder Include="Tests\" />
  </ItemGroup>

</Project>
